config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end

  resources :direct_messages
  get 'edit_profile' => 'users#edit'
  patch 'profile' => 'users#update'

  resources :uploads

  root to: "chatrooms#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/chatroom.rb
class Chatroom
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  include Mongoid::Paperclip
  field :name, type: String
  field :direct_message, type: Boolean, default: false
  has_many :chatroom_users, dependent: :destroy
  has_many :messages, dependent: :destroy
  scope :public_channels, ->{ where(direct_message: false) }
  scope :direct_messages, ->{ where(direct_message: true) }
  def self.direct_message_for_users(users)
    user_ids = users.map(&:id).sort
    name = "DM:#{user_ids.join(":")}"

    if chatroom = direct_messages.where(name: name).first
      chatroom
    else
      # create a new chatroom
      chatroom = new(name: name, direct_message: true)
      chatroom.save
      chatroom
    end
  end

  def Users
    User.in(id: chatroom_users.pluck(:user_id))
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.public_channels
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
    @messages = @chatroom.messages.order(created_at: :desc).limit(100).reverse
    @chatroom_user = current_user.chatroom_users.find_by(chatroom_id: @chatroom.id)
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|

      if @chatroom.save
        @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/views/chatrooms/_form.html.erb
<%= form_for(@chatroom) do |f| %>
  <div class="modal-header"></div>
  <a href= <%= chatrooms_path %> class="button close" data-dismiss="modal" type="button" >x</a>
  <h4 id="new-group-title" class="modal-title">New Channel</h4>
  <div class="modal-body">
    <div class="form-group">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter name Channels'%>
    </div>
  </div>
  <div class="modal-footer">
    <a href= <%= chatrooms_path %> class="btn btn-default" data-dismiss="modal" type="button">Close</a>
    <%= f.button :submit, value: "Save", class: 'btn btn-primary btn-share-file' %>
  </div>
<% end %>

app/views/chatrooms/index.html.erb
<div class="header">
  <div class="team-menu"><%= link_to 'TTV Chat', chatrooms_path, class: 'link-color'%></div>
  <div class="channel-menu">
    <span class="channel-menu_name"><span class="channel-menu_prefix">#</span> List Channel</span>
  </div>
</div>
<div class="main">
  <div class="listings">
    <div class="listings_channels">
      <h2 class="listings_header">Channels</h2>
      <ul class="channel_list">
        <% current_user.chatrooms.public_channels.each do |chatroom| %>
            <li class="channel"><span><%= link_to "# #{chatroom.name}", chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} %></span></li>
        <% end %>
      </ul>
    </div>
    <div class="listings_direct-messages">
      <h2 class="listings_header">Direct Messages</h2>
      <ul class="channel_list">
        <li class="channel">
          <% (User.all - [current_user]).each do |user| %>
            <ul>
              <li><span class="avatar"><%= image_tag(user.avatar.url(:original))%></span>
              <%= link_to user.email, direct_message_path(user.id), data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_message_for_users([current_user, user]).id } %></li>
            </ul>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="message-history">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @chatrooms.public_channels.each do |chatroom| %>
          <tr style="line-height: 50px;">
            <td id="list-room" style="width: 80%;"><%= chatroom.name %></td>
            <td><%= link_to "Join Channel", chatroom_chatroom_users_path(chatroom), class: 'btn btn-success' ,method: :post %></td>
              <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <!-- <td><%= link_to "Leave", chatroom_chatroom_users_path(chatroom), method: :delete %></td> -->
          </tr>
        <% end %>

      </tbody>

      <div id="myModal" class="chatroom-modal modal fade">
        <div class="modal-dialog">
          <div class="modal-content">
          </div>
        </div>
      </div>
    </table>
    <button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#myModal">
       <%= link_to 'New Channel', new_chatroom_path %>
    </button>
  </div>
</div>
<div class="footer">
  <div class="user-menu">
    <span class="user-menu_profile-pic">
    <% if user_signed_in? %>
      <div class="round-image-50">
        <%= image_tag(current_user.avatar.url(:original)) %>
      </div>
      <% end %>
    </span>
    <span class="user-menu_username"><%= link_to("#{current_user.email}", edit_profile_path, class: 'link-color' )%></span>
    <span class="connection_status">online</span>
    <span class="logout"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></span>
  </div>
</div>

app/views/chatrooms/new.html.erb
<div class="header">
  <div class="team-menu"><%= link_to 'TTV Chat', chatrooms_path, class: 'link-color'%></div>
  <div class="channel-menu">
    <span class="channel-menu_name"><span class="channel-menu_prefix">#</span> New Channel</span>
  </div>
</div>
<div class="main">
  <div class="listings">
    <div class="listings_channels">
      <h2 class="listings_header">Channels</h2>
      <ul class="channel_list">
        <% current_user.chatrooms.public_channels.each do |chatroom| %>
            <li class="channel"><span><%= link_to "# #{chatroom.name}", chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} %></span></li>

        <% end %>
      </ul>
    </div>
    <div class="listings_direct-messages">
      <h2 class="listings_header">Direct Messages</h2>
      <ul class="channel_list">
        <li class="channel">
          <% (User.all - [current_user]).each do |user| %>
            <ul>
              <li><span class="avatar"><%= image_tag(user.avatar.url(:original))%></span>
              <%= link_to user.email, direct_message_path(user.id), data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_message_for_users([current_user, user]).id } %></li>
            </ul>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="message-history" id="messages">
  <%= render partial: 'form', locals: { title: 'New Channel' } %>
  </div>
</div>
<div class="footer">
  <div class="user-menu">
    <span class="user-menu_profile-pic">
    <% if user_signed_in? %>
      <div class="round-image-50">
      </div>
      <% end %>
    </span>
    <span class="user-menu_username"><%= link_to("#{current_user.email}", edit_profile_path, class: 'link-color' )%></span>
    <span class="connection_status">online</span>
    <span class="logout"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></span>
  </div>

</div>

app/views/chatrooms/show.html.erb
 <div class="header">
  <div class="team-menu"><%= link_to 'TTV Chat', chatrooms_path, class: 'link-color'%></div>
  <div class="channel-menu">
    <% if controller.controller_name == "direct_messages" %>
      <% @users.each do |user|%>
        <span>#</span><span class="channel-menu_name"><%= user.email%></span>
      <% end %>
    <% else %>
      <span class="channel-menu_name">
      <span class="channel-menu_prefix">#</span>
      <%= @chatroom.name%>
    </span>
    <% end %>

    <span>
      <%= link_to "Leave Chat", chatroom_chatroom_users_path(@chatroom), method: :delete %>
    </span>
  </div>
</div>
<div class="main">
  <div class="listings">
    <div class="listings_channels">
      <h2 class="listings_header">Channels</h2>
      <ul class="channel_list">
        <% current_user.chatrooms.public_channels.each do |chatroom| %>
            <li class="channel"><span><%= link_to "# #{chatroom.name}", chatroom, data: {behavior: "chatroom-link", chatroom_id: chatroom.id} %></span></li>
        <% end %>
      </ul>
    </div>
    <div class="listings_direct-messages">
      <h2 class="listings_header">Direct Messages</h2>
      <ul class="channel_list">
        <li class="channel">
          <% (User.all - [current_user]).each do |user| %>
            <ul>
              <li><span class="avatar"><%= image_tag(user.avatar.url(:original))%></span>
              <%= link_to user.email, direct_message_path(user.id), data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_message_for_users([current_user, user]).id } %></li>
            </ul>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div data-behavior='messages' data-chatroom-id='<%= @chatroom.id%>' class="message-history" id="messages">
    <%= render @messages %>
     <div id="videos">
        <div id="subscriber"></div>
        <div id="publisher"></div>
    </div>
  </div>
</div>
<div class="footer">
  <div class="user-menu">
    <span class="user-menu_profile-pic">
    <% if user_signed_in? %>
      <div class="round-image-50">
        <!-- <%= image_tag(current_user.avatar.url(:original)) %> -->
      </div>
      <% end %>
    </span>
    <span class="user-menu_username"><%= link_to("#{current_user.email}", edit_profile_path, class: 'link-color' )%></span>
    <span class="connection_status">online</span>
    <span class="logout"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></span>
    </div>
    <div class="input-box">
    <%= form_for [@chatroom, Message.new],:html => {  'enctype' => "multipart/form-data", :multipart => true  } do |f| %>
      <%= f.text_area :content, rows: 1, class: "form-control input-box_text", id:"message_input",autofocus: true %>
    <% end %>

    <%= form_for Upload.new, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
      <%= f.file_field :attachment %>
    <% end %>

  </div>
</div>